CurrencyConverter/CurrencyConverter/Controllers/ConvertController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CurrencyConverter.currencyData;

namespace CurrencyConverter.Controllers
{
    public class ConvertController : Controller
    {
        private ConvertDataEntities2 db = new ConvertDataEntities2();

        // GET: Convert
        public ActionResult Index()
        {
            var converts = db.converts.Include(c => c.currency);
            return View(converts.ToList());
        }



        // GET: Convert/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            convert convert = db.converts.Find(id);
            if (convert == null)
            {
                return HttpNotFound();
            }
            return View(convert);
        }

        // POST: Convert/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            convert convert = db.converts.Find(id);
            db.converts.Remove(convert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CurrencyConverter/CurrencyConverter/Controllers/CurrencyModelController.cs
using CurrencyConverter.currencyData;
using CurrencyConverter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CurrencyConverter.Controllers
{
    public class CurrencyModelController : Controller
    {
        private ConvertDataEntities2 db = new ConvertDataEntities2();
        // GET: CurrencyModel
        public ActionResult Index()
        {
            var codeList = db.exchange_rates.Select(c => c.currency_code).ToList();
            ViewBag.data = codeList;
            return View();
        }

        [HttpPost]
        public ActionResult Index(ConvertModel model)
        {
            var codeList = db.exchange_rates.Select(c => c.currency_code).ToList();
            ViewBag.data = codeList;
            ViewBag.Message = null;
            if (getAmount(model.CurrTo, model.AmountTo) >= 3000 && model.Comment == null)
            {
                
                ViewBag.Message = "Please enter comment";

                return View();
            }
            convert temp = new convert();
            
            temp.currency_from = model.CurrFrom;
            temp.currency_to = model.CurrTo;
            temp.amount_from = model.AmountFrom;
            temp.amount_to = model.AmountTo;
            temp.comment = model.Comment;
            temp.convert_date = DateTime.Now;
            db.converts.Add(temp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult getCoeficient(string fromCurr, string toCurr)
        {
            var fromRate = db.exchange_rates.FirstOrDefault(e => e.currency_code == fromCurr).sell_rate;
            var toRate = db.exchange_rates.FirstOrDefault(e => e.currency_code == toCurr).buy_rate;
            return Json(Math.Round(fromRate/toRate, 4), JsonRequestBehavior.AllowGet);
        }

        
        public JsonResult getAmountInGel(string toCurr, decimal amount)
        {
            var toRate = db.exchange_rates.FirstOrDefault(e => e.currency_code == toCurr).buy_rate;
            return Json(Math.Round(amount * toRate, 4), JsonRequestBehavior.AllowGet);
        }

        private decimal getAmount(string toCurr, decimal amount)
        {
            var toRate = db.exchange_rates.FirstOrDefault(e => e.currency_code == toCurr).buy_rate;
            return Math.Round(amount * toRate, 4);
        }

    }
}

CurrencyConverter/CurrencyConverter/Views/CurrencyModel/Index.cshtml
@model CurrencyConverter.Models.ConvertModel

@{
    ViewBag.Title = "Index";
}

<h2>კონვერტაცია</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CurrTo, "მისაღები ვალუტა", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CurrFrom", new SelectList(ViewBag.data), htmlAttributes: new { @class = "form-control", id = "FromCurr" })
                @Html.ValidationMessageFor(model => model.CurrTo, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.AmountFrom, "მისაღები თანხა", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountFrom, new { htmlAttributes = new { @class = "form-control", id = "AmountFrom" } })
                @Html.ValidationMessageFor(model => model.AmountFrom, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CurrTo, "გასაცემი ვალუტა", htmlAttributes: new { @class = "contr ol-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CurrTo", new SelectList(ViewBag.data), htmlAttributes: new { @class = "form-control", id = "ToCurr"})
                @Html.ValidationMessageFor(model => model.CurrTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AmountTo, "გასაცემი თანხა", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountTo, new { htmlAttributes = new { @class = "form-control" , id = "AmountTo" } })
                @Html.ValidationMessageFor(model => model.AmountTo, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Comment, "კომენტარი", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", id = "comment"} })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger"})
                @if (ViewBag.Message != null)
                {
                <Label class = "text-danger"  id="commentVal"> Please enter comment</Label>
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="კონვერტაცია" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("კონვერტაციები", "Index", "Convert")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script>
        $("#document").ready(function () {

            $('#AmountFrom').on('change', function () {
                $.ajax({
                    type: 'POST',
                    url: '/CurrencyModel/getCoeficient?fromCurr=' + $('#FromCurr').val() + '&toCurr=' + $('#ToCurr').val(),
                    contextType: 'application/json; charset=utf-8',
                    contentType: 'html',

                    success: function (result) {
                        $('#AmountTo').val($('#AmountFrom').val() * result)
                    },
                    error: function (error) {
                        alert("Request: " + JSON.stringify(error));
                    }
                });
            });
            $('#AmountTo').on('change' , function () {
                $.ajax({
                    type: 'POST',
                    url: '/CurrencyModel/getCoeficient?fromCurr=' + $('#FromCurr').val() + '&toCurr=' + $('#ToCurr').val(),
                    contextType: 'application/json; charset=utf-8',
                    contentType: 'html',
                    success: function (result) {
                        $('#AmountFrom').val($('#AmountTo').val() / result)
                    },
                    error: function (error) {
                        alert("Request: " + JSON.stringify(error));
                    }
                });
            });

            $('#FromCurr').change(function () {
                $.ajax({
                    type: 'POST',
                    url: '/CurrencyModel/getCoeficient?fromCurr=' + $('#FromCurr').val() + '&toCurr=' + $('#ToCurr').val(),
                    contextType: 'application/json; charset=utf-8',
                    contentType: 'html',

                    success: function (result) {
                        $('#AmountTo').val($('#AmountFrom').val() * result)
                    },
                    error: function (error) {
                        alert("Request: " + JSON.stringify(error));
                    }
                });
            });
            $('#ToCurr').change(function () {
                $.ajax({
                    type: 'POST',
                    url: '/CurrencyModel/getCoeficient?fromCurr=' + $('#FromCurr').val() + '&toCurr=' + $('#ToCurr').val(),
                    contextType: 'application/json; charset=utf-8',
                    contentType: 'html',

                    success: function (result) {
                        $('#AmountTo').val($('#AmountFrom').val() * result)
                    },
                    error: function (error) {
                        alert("Request: " + JSON.stringify(error));
                    }
                });
            });
        })
    </script>
}