CurrencyConverter/CurrencyConverter/Controllers/ConvertController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CurrencyConverter.currencyData;

namespace CurrencyConverter.Controllers
{
    public class ConvertController : Controller
    {
        private ConvertDataEntities2 db = new ConvertDataEntities2();

        // GET: Convert
        public ActionResult Index()
        {
            var converts = db.converts.Include(c => c.currency);
            return View(converts.ToList());
        }



        // GET: Convert/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            convert convert = db.converts.Find(id);
            if (convert == null)
            {
                return HttpNotFound();
            }
            return View(convert);
        }

        // POST: Convert/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            convert convert = db.converts.Find(id);
            db.converts.Remove(convert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CurrencyConverter/CurrencyConverter/Controllers/CurrencyModelController.cs
using CurrencyConverter.currencyData;
using CurrencyConverter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CurrencyConverter.Controllers
{
    public class CurrencyModelController : Controller
    {
        private ConvertDataEntities2 db = new ConvertDataEntities2();
        // GET: CurrencyModel
        public ActionResult Index()
        {
            var codeList = db.exchange_rates.Select(c => c.currency_code).ToList();
            ViewBag.data = codeList;
            return View();
        }

        [HttpPost]
        public ActionResult Index(ConvertModel model)
        {
            var codeList = db.exchange_rates.Select(c => c.currency_code).ToList();
            ViewBag.data = codeList;
            ViewBag.Message = null;
            if (getAmount(model.CurrTo, model.AmountTo) >= 3000 && model.Comment == null)
            {
                
                ViewBag.Message = "Please enter comment";

                return View();
            }
            convert temp = new convert();
            
            temp.currency_from = model.CurrFrom;
            temp.currency_to = model.CurrTo;
            temp.amount_from = model.AmountFrom;
            temp.amount_to = model.AmountTo;
            temp.comment = model.Comment;
            temp.convert_date = DateTime.Now;
            db.converts.Add(temp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult getCoeficient(string fromCurr, string toCurr)
        {
            var fromRate = db.exchange_rates.FirstOrDefault(e => e.currency_code == fromCurr).sell_rate;
            var toRate = db.exchange_rates.FirstOrDefault(e => e.currency_code == toCurr).buy_rate;
            return Json(Math.Round(fromRate/toRate, 4), JsonRequestBehavior.AllowGet);
        }

        
        public JsonResult getAmountInGel(string toCurr, decimal amount)
        {
            var toRate = db.exchange_rates.FirstOrDefault(e => e.currency_code == toCurr).buy_rate;
            return Json(Math.Round(amount * toRate, 4), JsonRequestBehavior.AllowGet);
        }

        private decimal getAmount(string toCurr, decimal amount)
        {
            var toRate = db.exchange_rates.FirstOrDefault(e => e.currency_code == toCurr).buy_rate;
            return Math.Round(amount * toRate, 4);
        }

    }
}

CurrencyConverter/CurrencyConverter/Views/Convert/Delete.cshtml
@model CurrencyConverter.currencyData.convert

@{
    ViewBag.Title = "Delete";
}

<h2>კონვერტაციის წაშლა</h2>

<h3>დარწმუნებული ხართ, რომ გსურთ კონვერტაციის წაშლა?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            მისაღები ვალუტა
        </dt>
        <dd>
            @Html.DisplayFor(model => model.currency_from)
        </dd>
        <dt>
            გასაცემი ვალუტა
        </dt>
        <dd>
            @Html.DisplayFor(model => model.currency_to)
        </dd>

        <dt>
            მისაღები თანხა
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount_from)
        </dd>

        <dt>
            გასაცემი თანხა
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount_to)
        </dd>

        <dt>
            კონვერტაციის თარიღი
        </dt>

        <dd>
            @Html.DisplayFor(model => model.convert_date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="წაშლა" class="btn btn-default" /> |
            @Html.ActionLink("უკან დაბრუნება", "Index")
        </div>
    }
</div>

CurrencyConverter/CurrencyConverter/Views/Convert/Index.cshtml
@model IEnumerable<CurrencyConverter.currencyData.convert>

@{
    ViewBag.Title = "Index";
}

<h2>კონვერტაციები</h2>

<p>
    @Html.ActionLink("კონვერტაციის შესრულება", "Index", "CurrencyModel")
</p>
<table class="table">
    <tr>
        <th>
            მისაღები ვალუტა
        </th>
        <th>
            გასაცემი ვალუტა
        </th>
        <th>
            მისაღები თანხა
        </th>
        <th>
            გასაცემი თანხა
        </th>
        <th>
           კონვერტაციის თარიღი
        </th>
        <th>
            კომენტარი
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.currency_from)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.currency_to)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount_from)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount_to)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.convert_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.comment)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>